# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build and Publish

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
  
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v3
      with:
        versionSpec: '6.0.x'

    - name: Determine Version
      id:   gitversion # id to later be referenced
      uses: gittools/actions/gitversion/execute@v3
      with:
        updateAssemblyInfo: true

    - name: Display GitVersion outputs
      run: |
        echo "Assembly File Version (environment variable AssemblySemFileVer): ${{ env.AssemblySemFileVer }}"
        echo "Assembly Version (environment variable AssemblySemVer): ${{ env.AssemblySemVer }}"
        echo "SemVer (environment variable semVer): ${{ env.semVer }}"

    - name: Restore dependencies
      run: dotnet restore

    - name: Build and Pack
      run: dotnet pack --no-restore -p:PackageVersion=${{ env.semVer }} --output "artifacts"

    - name: Publish NuGet package
      uses: nuget/nuget-publish@1
      with:
        nuget-api-key: ${{ secrets.NUGET_API_KEY }}
        nuget-version: ${{ env.semVer }}
        nuget-package: "artifacts/*.nupkg"
        nuget-endpoint: "https://api.nuget.org/v3/index.json"
